name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build and test (All)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: olafurpg/setup-scala@v10
      - name: Cache SBT
        uses: coursier/cache-action@v3
      - run: sbt +clean +test

  coverage:
    name: Generate coverage report (2.13.14 JVM only)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: olafurpg/setup-scala@v10
      - name: Cache SBT
        uses: coursier/cache-action@v3
      - run: sbt ++2.13.14 coverage test coverageReport
      - name: Upload code coverage data
        run: bash <(curl -s https://codecov.io/bash)
    
